### ISSUE TITLE
Dosya yükleme

### ISSUE THREAD

**Issue by ghost** [tgrl5000/HizliResim-PHP-API#1]
Sadece link olarak yüklemek mümkün ve sorunsuz çalışıyor. Direkt link döndürmesini takdir ettim. 
Ama dosya seçerek yüklemek de mümkün olmalı

**Comment by tgrl5000** [comment]
En kısa zamanda eklenecek teşekkürler öneriniz için.

**Comment by ertanyildiz** [comment]
dosya yükleme sadece .jpg dosyayı için geçerli sanırım.

**Comment by tugaysocal** [comment]
url'den jpg olarak yüklediğim dosyanın uzantısını kendisi png yapıyor bunu nasıl çözebiliriz?

**Comment by tgrl5000** [comment]
![](http://i.hizliresim.com/o0nmzk.png)
Kontrol ettim jpg olarak yüklüyor jpg uzantılı dosyayı.Yüklemeyi denediğiniz dosyanın jpg dosyası olduğuna emin misiniz ? İsterseniz url'i paylaşın kontrol edelim.

**Comment by tugaysocal** [comment]
Örneğin, url olarak https://app.link4fb.net/files/QXhJvO-01-20.jpg bu görseli yüklüyorum ve bana döndüğü result bu şekilde : http://i.hizliresim.com/VPg3dV.png

Sorun neyden kaynaklanabilir?
teşekkürler.

**Comment by tgrl5000** [comment]
Attığın resmi kontrol ettim.Attığın resim jpg uzantılı bir png dosyası.Eğer dosyayı indirip herhangi bir metin editörüyle açarsan göreceksin ki dosya 
‰PNG
ile başlıyor.Yani bu uzantısı değiştirilmiş bir png dosyası.Hızlıresim uzantıya bakmadan doğrudan dosya türünü okuyor ve ona göre uzantıyı yeniden adlandırıyor.Bu yüzden dosyayı önce resim editörlerinden jpg formatına çevirip sonra yüklemelisin ya da png olarak kullanmalısın.

**Comment by tugayocal** [comment]
Hizliresimin bize uzantıyı da dönebilmesi için ek bir öneriniz olur mu acaba yada nasıl alabiliriz

**Comment by tgrl5000** [comment]
Eğer biraz daha beklerseniz hem normal dosya yükleme hem de url üzerinden dosya yükleme özelliklerini geliştiriyorum.Ayrıca bu özelliği de ekleyeceğim.İstenen dosya türünden başka bir türe çevirme özelliğini de yapıyorum.Fakat şu an geliştirme aşamasında biter bitmez buraya yükleyeceğim.Lütfen takipte kalın.

**Comment by tugayocal** [comment]
Teşekkürler, bekliyorum.

**Comment by tgrl5000** [comment]
Geliştirmeler bitti birazdan Türkçe dökümantasyonunu da hazırlayıp yayınlayacağım.Her hangi bir problem olursa lütfen yine bildirmekten çekinmeyin.
Dosyadan yükleme ve bir çok özellik eklenmiş durumda olmakla beraber tüm sınıf yapısı ve isimleri baştan aşağı değişmiştir.İyi kodlamalar.
